# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

  workflow_dispatch:
    inputs:
      specialNotes:
        description: 'Notes'
        required: false
        type: string

env:
  NOTES: ${{ inputs.specialNotes }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    if: ${{ github.event.pull_request.merged == true || inputs.specialNotes != null }}
    steps:
      - uses: actions/checkout@v3

      - name: NOTES ARE NOT NULL
        run: echo Hello, world! ${{ env.NOTES }}
        if: ${{ env.NOTES != null }}

      - name: NOTES ARE NULL
        run: echo Hello, world!
        if: ${{ env.NOTES == null }}

      - name: Push changes
        run: |
          date > generated.txt \
          git config user.name github-actions \
          git config user.email github-actions@github.com \
          git add . \
          git commit -m "generated" \
          git push \

      - name: ECHO
        run: echo Hello, world!
