# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

  workflow_dispatch:
    inputs:
      specialNotes:
        description: 'Notes'
        required: false
        type: string

env:
  NOTES: ${{ inputs.specialNotes }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: test1
      run: echo hoge
      if: ( 'a' == 'a' )

    - name: test2
      run: echo hoge
      if: ( 'a' == 'b' )

    - name: test3
      run: echo hoge
      if: &gt;
        'a' == 'a'

    - name: test4
      run: echo hoge
      if: &gt;
        'a' == 'b'

    - name: test5
      run: echo hoge
      if: &gt;
        ${{ 'a' == 'a' }}

    - name: test6
      run: echo hoge
      if: &gt;
        ${{ 'a' == 'b' }}